city_to_province = {
        "北京": "北京",
        "上海": "上海",
        "广州": "广东省",
        "深圳": "广东省",
        "杭州": "浙江省",
        "义乌": "浙江省",
        "南京": "江苏省",
        "成都": "四川省",
        "重庆": "重庆",
        "武汉": "湖北省",
        "西安": "陕西省",
        "张家港": "江苏省",
        "廊坊": "河北省",
        '宁波': '浙江省',
        "济南": "山东省",
        "南昌": "江西省",
        "长春": "吉林省",
        "芜湖": "安徽省",
        "佛山": "广东省",
        "连云港": "江苏省",
        "游州": "安徽省",
        "金华": "浙江省",
        "宜春": "江西省",
        "长沙": "湖南省",
        '光阳': '河南省',
        '洛阳': '河南省',
        '东乡': '江西省',
        '新余': '江西省',
        '宜都': '湖北省',
        '苏州': '江苏省',
        '涿州': '河北省',
        '台州': '浙江省',
        '高州': '广东省',
        '常州': '江苏省',    
        '泉州': '福建省',
        '湖州':  '浙江省',
        '东莞': '广东省',
        '江门': '广东省',
        '衡阳': '湖南省',
        '南通': '江苏省',
        '江门': '广东省',
        '衡阳': '湖南省',
        '黄山': '安徽省',
        '周口': '河南省',
        '南平': '福建省',
        '高州': '广东省',
        '汲州': '河南省'
    }

country_city_dict = {
        ('Shenzhen', 'Guangdong', 'Mainland China'),
        ('Guangzhou', 'Guangdong', 'Mainland China'),
        ('Foshan', 'Guangdong', 'Mainland China'),
        ('Bengbu', 'Anhui', 'Mainland China'),
        ('Hefei', 'Anhui', 'Mainland China'),
        ('Nanning', 'Guangxi', 'Mainland China'),
        ('Shanghai', 'Shanghai', 'Mainland China'),
        ('Suqian', 'Jiangsu', 'Mainland China'),
        ('Langfang', 'Hebei', 'Mainland China'),
        ('China', 'China', 'Mainland China'),
        ('Zhangjiagang', 'Suzhou', 'Mainland China'),
        ('Yiwu', 'Zhejiang', 'Mainland China'),
        ('Lianyungang', 'Jiangsu', 'Mainland China'),
        ('Nanjing', 'Jiangsu', 'Mainland China'),
        ('Ningbo', 'Zhejiang', 'Mainland China'),
        ('Jinan', 'Shandong', 'Mainland China'),
        ('Nanchang', 'Jiangxi', 'Mainland China'),
        ('Yiwu', 'Zhejiang', 'Mainland China'),
        ('Beijing', 'Hebei', 'Mainland China'),
        ('Foshan', 'Guangdong', 'Mainland China'),
        ("Xi'an", 'Shaanxi', 'Mainland China'),
        ('Wuhu', 'Anhui', 'Mainland China'),
        ('Lianyungang', 'Jiangsu', 'Mainland China'),
        ('Changchun', 'Jilin', 'Mainland China'),
        ('Jinhua', 'Zhejiang', 'Mainland China'),
        ('Changsha', 'Hunan', 'Mainland China'),
        ('Guangyang', 'Henan', 'Mainland China'),
        ('Xinyu', 'Jiangxi', 'Mainland China'),
        ('Yidu', 'Hubei', 'Mainland China'),
        ('Lanzhou', 'Jiangsu', 'Mainland China'),
        ('Zhuozhuo', 'Hebei', 'Mainland China'),
        ('Taizhou', 'Zhejiang', 'Mainland China'),
        ('Gaozhou', 'Guangdong', 'Mainland China'),
        ('Changzhou', 'Jiangsu', 'Mainland China'),
        ('Quanzhou', 'Fujian', 'Mainland China'),
        ('Huzhou', 'Zhejiang', 'Mainland China'),
        ('Suzhou', 'Jiangsu', 'Mainland China'),
        ('Hangzhou', 'Zhejiang', 'Mainland China'),
        ('Dazhou', 'Hebei', 'Mainland China'),
        ('Dongguan', 'Guangdong', 'Mainland China'),
        ('Jiangmen', 'Guangdong', 'Mainland China'),
        ('Hengyang', 'Hunan', 'Mainland China'),
        ('Nantong', 'Jiangsu', 'Mainland China'),
        ('Dazhou', 'Hebei', 'Mainland China'),
        ('Luoyang', 'Henan', 'Mainland China'),
        ('Huangshan', 'Anhui', 'Mainland China'),
        ('Zhoukou', 'Henan', 'Mainland China'),
        ('Nanping', 'Fujian', 'Mainland China'),
        ('Jizhou', 'Henan', 'Mainland China'),
        ('Dongxiang', 'Jiangxi', 'Mainland China'),
        ('Guigang', 'Guangxi', 'Mainland China'),
        ('Zhengzhou', 'Henan', 'Mainland China'),
        ('Zhangzhou', 'Fujian', 'Mainland China'), 
        ('Songyuan', 'Jilin', 'Mainland China'),
        ('Haikou', 'Hainan', 'Mainland China'),
        ('Dezhou', 'Shandong', 'Mainland China'),
        ('Wuhan', 'Hubei', 'Mainland China'),
        ('Putian', 'Fujian', 'Mainland China'),
        ('Yangzhou', 'Jiangsu', 'Mainland China'),
        ('Yueyang', 'Hunan', 'Mainland China'),
        ('Wuhan', 'Hubei', 'Mainland China'),
        ('Foggia', 'Puglia', 'Italy'),
        ('Albolote', 'Granada', 'Spain'),
        ('Santander', 'Cantabria', 'Spain'),
        ('Albacete', 'Albacete', 'Spain')
}

country_area_dict = {
        'Mainland China': 'Greater China',
        'Hong Kong': 'Greater China',
        'Spain': 'Europe',
        'Italy': 'Europe',
        'Germany': 'Europe'
}
